FROM ruby:2.5.8-alpine3.12

RUN mkdir -p /app
WORKDIR /app

COPY . ./
RUN bin/install_system_deps.sh && \
  gem install bundler --version '= 1.16.6' && \
  bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve"]
