version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bundle exec jekyll serve -H 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - .:/app
